title: Glerison Lima
description: Este é meu Blog iremos falar sobre os mais diversos assuntos sobre tecnologia

url: https://glerisonlima.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: glerisonlima
   twitter: GlerisonL
   facebook: glerison.lima
   email: glerisonlima@gmail.com

google_analytics: "UA-58263416-1"
